org: cockpit
app: pit
service: api

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app


provider:
  name: aws
  runtime: python3.8
  timeout: 30
  iam:
    role:
      statements:
        # Allow functions to list all buckets
        - Effect: Allow
          Action: 's3:ListBucket'
          Resource: '*'
        # Allow functions to read/write objects in a bucket
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
          Resource:
            - 'arn:aws:s3:::bot-acr-guidelines/*'


functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'
  # rateHandler:
  #   handler: monitor.launch
  #   events:
  #     # Invoke Lambda function every minute
  #     - schedule: rate(10 minutes)
  cronHandler:
    handler: monitor.launch
    events:
      - schedule: cron(0 9 ? * MON *)


plugins:
  - serverless-wsgi
  - serverless-python-requirements
